# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: |
      curl -fsSL https://deno.land/x/install/install.sh | sh
      curl https://nim-lang.org/choosenim/init.sh -sSf | sh
      echo 'export PATH=/home/gitpod/.nimble/bin:$PATH' >>~/.bashrc
      echo 'export DENO_INSTALL="/home/gitpod/.deno"' >>~/.bashrc
      echo 'export PATH="$DENO_INSTALL/bin:$PATH"' >>~/.bashrc
      source ~/.bash_profile
      pip install numpy
      pip install scipy
      nimble install inim -y
      nimble install arraymancer -y

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
